// STB actions
export const GET_ALL_PHASES = 'GET_ALL_PHASES';
export const GET_ALL_BOUQUETS = 'GET_ALL_BOUQUETS';
export const GET_ALL_CHANNELS = 'GET_ALL_CHANNELS';
export const CHOOSE_CHANNEL = 'CHOOSE_CHANNEL';
export const RUN_CHANNEL = 'RUN_CHANNEL';